# Generated by Django 6.0.4 on 2026-05-14 06:31

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', '全新'), ('like_new', '几乎全新'), ('good', '轻微使用痕迹'), ('fair', '明显使用痕迹')], max_length=100, null=True, verbose_name='成色'),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_notes',
            field=models.TextField(default='', verbose_name='交付说明'),
        ),
        migrations.AddField(
            model_name='listing',
            name='physical_delivery_method',
            field=models.CharField(blank=True, choices=[('meetup', '线下自提/面交'), ('shipping', '快递发货'), ('both', '均可')], max_length=300, null=True, verbose_name='实体商品交付方法'),
        ),
        migrations.AddField(
            model_name='listing',
            name='virtual_valid_until',
            field=models.DateField(blank=True, null=True, validators=[catalog.models.valid_virtual_until_time], verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '在售'), ('reserved', '交易占用'), ('sold', '已售出'), ('withdrawn', '已下架')], default='draft', verbose_name='商品状态'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/%d', validators=[catalog.models.valid_image_size], verbose_name='商品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.listing', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
