# Generated by Django 6.0.4 on 2026-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_listing_condition_listing_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', verbose_name='交付说明'),
        ),
    ]
