# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    """为公开商品列表筛选和排序补充数据库索引。"""

    dependencies = [
        ("catalog", "0005_alter_listing_owner"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "-published_at"],
                name="listing_status_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "-published_at"],
                name="listing_cat_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["item_type", "-published_at"],
                name="listing_type_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="listing_price_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["published_at"], name="listing_pub_idx"),
        ),
    ]
