# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    """为我的商品管理列表筛选和排序补充数据库索引。"""

    dependencies = [
        ("catalog", "0006_listing_public_list_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["owner", "-updated_at"],
                name="listing_owner_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["owner", "status", "-updated_at"],
                name="listing_owner_status_idx",
            ),
        ),
    ]
