# Generated by Codex for notifications app.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """创建站内通知模型。"""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("listing_commented", "商品收到评论"),
                            ("comment_replied", "评论收到回复"),
                            ("order_created", "买家创建订单"),
                            ("order_paid", "买家支付成功"),
                            ("order_delivered", "卖家发货或交付"),
                            ("order_completed", "订单完成"),
                        ],
                        max_length=40,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="通知标题")),
                ("content", models.CharField(max_length=300, verbose_name="通知内容")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("listing", "商品"),
                            ("order", "订单"),
                            ("comment", "评论"),
                        ],
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(verbose_name="目标 ID"),
                ),
                (
                    "target_url",
                    models.CharField(max_length=200, verbose_name="跳转地址"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="已读时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发用户",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="notif_recipient_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_at", "-created_at"],
                name="notif_recipient_read_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "-created_at"],
                name="notif_type_created_idx",
            ),
        ),
    ]
