# Generated by Django 6.0.4 on 2026-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_listing_image_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='市快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_detail_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='区快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='省快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_recipient_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收货人快照'),
        ),
    ]
