# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    """为订单列表筛选和排序补充数据库索引。"""

    dependencies = [
        ("orders", "0007_order_shipping_city_order_shipping_detail_address_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "-created_at"],
                name="order_buyer_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "-created_at"],
                name="order_seller_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status", "-created_at"],
                name="order_buyer_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "status", "-created_at"],
                name="order_seller_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_price"], name="order_price_idx"),
        ),
    ]
