# Generated by Django 6.0 on 2026-07-10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """创建订单评分数据表。"""

    dependencies = [
        ("orders", "0008_order_list_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="星级评分",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="评分时间")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_rating",
                        to="orders.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单评分",
                "verbose_name_plural": "订单评分",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
