# Generated by Django 6.0.4 on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="interactions.comment",
                verbose_name="父留言",
            ),
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="interaction_listing_088bf4_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["listing", "parent", "created_at", "id"],
                name="interaction_listing_parent_idx",
            ),
        ),
    ]
