# Generated by Django 6.0.4 on 2026-05-10 12:54

import django.core.validators
from django.db import migrations, models


def fill_empty_nickname(apps, schema_editor):
    """将历史空昵称回填为统一初始昵称。"""

    Profile = apps.get_model("users", "Profile")
    Profile.objects.filter(nickname__isnull=True).update(nickname="初始昵称")
    Profile.objects.filter(nickname="").update(nickname="初始昵称")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(fill_empty_nickname, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='初始昵称', max_length=10, validators=[django.core.validators.MinLengthValidator(1, message='用户昵称长度不能为空')], verbose_name='用户昵称'),
        ),
    ]
