# Generated by Django 6.0.4 on 2026-05-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_alter_listing_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer_diaplay_name",
                    models.CharField(max_length=20, verbose_name="买家名称"),
                ),
                (
                    "seller_display_name",
                    models.CharField(max_length=20, verbose_name="卖家名称"),
                ),
                (
                    "listing_title_snapshot",
                    models.CharField(max_length=50, verbose_name="商品名称"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待支付"),
                            ("cancelled", "已取消"),
                            ("awaiting_shipment", "待发货"),
                            ("awaiting_receipt", "待收货"),
                            ("completed", "已完成"),
                        ],
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="订单价格"
                    ),
                ),
                (
                    "payment_deadline",
                    models.DateTimeField(null=True, verbose_name="截止时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(null=True, verbose_name="支付成功时间"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(null=True, verbose_name="卖家确认交付时间"),
                ),
                (
                    "received_at",
                    models.DateTimeField(null=True, verbose_name="买家确认收货时间"),
                ),
                ("cancelled_at", models.DateTimeField(verbose_name="取消时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="买家",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="catalog.listing",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_as_seller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "indexes": [
                    models.Index(
                        fields=["buyer", "status"],
                        name="orders_orde_buyer_i_4a5ff4_idx",
                    ),
                    models.Index(
                        fields=["seller", "status"],
                        name="orders_orde_seller__912a3b_idx",
                    ),
                    models.Index(
                        fields=["listing", "status"],
                        name="orders_orde_listing_134a79_idx",
                    ),
                    models.Index(
                        fields=["status", "payment_deadline"],
                        name="orders_orde_status_e5c983_idx",
                    ),
                ],
            },
        ),
    ]
