# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """新增商品收藏和浏览历史数据表。"""

    dependencies = [
        ("catalog", "0007_listing_owner_list_indexes"),
        ("interactions", "0002_comment_parent_update_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="catalog.listing",
                        verbose_name="收藏商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品收藏",
                "verbose_name_plural": "商品收藏",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ListingViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now=True, verbose_name="浏览时间"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="catalog.listing",
                        verbose_name="浏览商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_view_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="浏览用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
                "ordering": ["-viewed_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="listingfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"),
                name="uniq_listing_favorite_user_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listingfavorite",
            index=models.Index(
                fields=["user", "-created_at"],
                name="favorite_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listingfavorite",
            index=models.Index(
                fields=["listing", "-created_at"],
                name="favorite_listing_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingviewhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"),
                name="uniq_listing_view_user_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listingviewhistory",
            index=models.Index(
                fields=["user", "-viewed_at"],
                name="view_user_viewed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listingviewhistory",
            index=models.Index(
                fields=["listing", "-viewed_at"],
                name="view_listing_viewed_idx",
            ),
        ),
    ]
